In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 5],])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [2]:
print(f'Матрица A:\n{A}')
print(f'Матрица U:\n{U}')
print(f'Матрица D:\n{D}')
print(f'Матрица V:\n{V}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  5]]
Матрица U:
[[ 0.12  0.21 -0.49 -0.79  0.27]
 [ 0.42 -0.39  0.4  -0.47 -0.53]
 [-0.03 -0.79 -0.59  0.15 -0.01]
 [ 0.76  0.32 -0.38  0.35 -0.23]
 [ 0.48 -0.26  0.33  0.06  0.77]]
Матрица D:
[[9.88 0.   0.  ]
 [0.   6.46 0.  ]
 [0.   0.   2.76]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.08 -0.29 -0.95]
 [ 0.55  0.81 -0.2 ]
 [ 0.83 -0.5   0.22]]


In [7]:
print(f'Матрица A:\n{A}')
print(f'Обратное проверочное преобразование:\n {np.dot(np.dot(U, D), V.T)}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  5]]
Обратное проверочное преобразование:
 [[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  5.]]


### Евклидова норма для матрицы А:

In [11]:
print(f'В соответствии с определением, Евклидова норма матрицы А = {D[0,0]}')

В соответствии с определением, Евклидова норма матрицы А = 9.884989484674286


### Норма Фробениуса для матрицы А:

In [25]:
fobD = np.sqrt(np.sum(s*s))
fobA = np.sqrt(np.sum(A*A))
print(f'Норма Фробениуса по матрице А: {fobA}')
print(f'Норма Фробениуса по матрице D: {fobD}')

Норма Фробениуса по матрице А: 12.12435565298214
Норма Фробениуса по матрице D: 12.124355652982139
