In [1]:
import numpy as np

### 1_1

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & -3 & -3 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & -3 & -3 \\ 
0 & 0 & -4 & -1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Система имеет бесконечное количество решений.

Общее решение:

$x_{4}=c$

$-4x_{3}-c=4 \; \Leftrightarrow \; x_{3}=(4+c)/-4$

$-x_{2}-3((4+с)/−4) - 3с=-2 \; \Leftrightarrow \; x_{2}=-3((4+с)/−4) - 3с + 2$

$x_{1}-3((4+с)/−4) - 3с + 2 - ((4+c)/-4) - 2с=0 \; \Leftrightarrow \; x_{1}=4((4+с)/−4) + 5с - 2$

### 1_2

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print('Основная матрица:')
print(A)
AA = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print('расширенная матрица:')
print(AA)
print(f'Ранг основной матрицы:{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы:{np.linalg.matrix_rank(AA)}')
print('rankA = rankAA = n, система определена, то есть имеет единственное решение')

Основная матрица:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
расширенная матрица:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг основной матрицы:3
Ранг расширенной матрицы:3
rankA = rankAA = n, система определена, то есть имеет единственное решение


In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
print('Основная матрица:')
print(A)
AA = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
print('расширенная матрица:')
print(AA)
print(f'Ранг основной матрицы:{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы:{np.linalg.matrix_rank(AA)}')
print('rankA < rankAA, система система несовместна')

Основная матрица:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
расширенная матрица:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг основной матрицы:1
Ранг расширенной матрицы:2
rankA < rankAA, система система несовместна


In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
print('Основная матрица:')
print(A)
AA = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
print('расширенная матрица:')
print(AA)
print(f'Ранг основной матрицы:{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы:{np.linalg.matrix_rank(AA)}')
print('rankA = rankAA < n, система имеет бесконечное количество решений')

Основная матрица:
[[ 1  2  5]
 [ 3  1 -8]]
расширенная матрица:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг основной матрицы:2
Ранг расширенной матрицы:2
rankA = rankAA < n, система имеет бесконечное количество решений


### 1_3

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
print('Основная матрица:')
print(A)
AA = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
print('расширенная матрица:')
print(AA)
print(f'Ранг основной матрицы:{np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы:{np.linalg.matrix_rank(AA)}')
print('rankA = rankAA = n, система определена, то есть имеет единственное решение')

Основная матрица:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
расширенная матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг основной матрицы:4
Ранг расширенной матрицы:4
rankA = rankAA = n, система определена, то есть имеет единственное решение


### 1_4

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

In [6]:
a = 0
b = 1
c = 0

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Основная матрица:')
print(A)
AA = np.array([[1, 2, 3, a], [4, 5, 6, b], [7, 8, 9, c]])
print('расширенная матрица:')
print(AA)

print(f'rankA =  {np.linalg.matrix_rank(A)} rankAA = {np.linalg.matrix_rank(AA)}')

if np.linalg.matrix_rank(A) < np.linalg.matrix_rank(AA):
    print ('Система несовместна!')
else:
    print ('Система совместна!')

Основная матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
расширенная матрица:
[[1 2 3 0]
 [4 5 6 1]
 [7 8 9 0]]
rankA =  2 rankAA = 3
Система несовместна!


### 2_1

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [28]:
A = np.array([[1, -2], [3, -4]])
print('Основная матрица:')
print(A)
det1 = int(np.linalg.det(A))
print(f'Определитель: {det1}')

a = 1
b = 7

A = np.array([[a, -2], [b, -4]])
print(A)
det2 = int(np.linalg.det(A))
print(f'Определитель: {det2}')

A = np.array([[1, a], [3, b]])
print(A)
det3 = int(np.linalg.det(A))
print(f'Определитель: {det3}')


print (f'x1 = {det2/det1}')
print (f'x2 = {det3/det1}')


Основная матрица:
[[ 1 -2]
 [ 3 -4]]
Определитель: 2
[[ 1 -2]
 [ 7 -4]]
Определитель: 9
[[1 1]
 [3 7]]
Определитель: 3
x1 = 4.5
x2 = 1.5


б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [40]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print('Основная матрица:')
print(A)
det1 = round(np.linalg.det(A),1)
print(f'Определитель: {det1}')

a = 10
b = -2
c = 1

A = np.array([[a, -1, 5], [b, 1, -3], [c, 4, 1]])
print(A)
det2 = round(np.linalg.det(A),1)
print(f'Определитель: {det2}')

A = np.array([[2, a, 5], [1, b, -3], [2, c, 1]])
print(A)
det3 = round(np.linalg.det(A),1)
print(f'Определитель: {det3}')

A = np.array([[2, -1, a], [1, 1, b], [2, 4, c]])
print(A)
det4 = round(np.linalg.det(A),1)
print(f'Определитель: {det4}')


print (f'x1 = {det2/det1}')
print (f'x2 = {det3/det1}')
print (f'x3 = {det4/det1}')


Основная матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель: 43.0
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель: 86.0
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель: -43.0
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель: 43.0
x1 = 2.0
x2 = -1.0
x3 = 1.0
