### 1_1

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 0], [2, 1], [10, 5], [2, 1]])
B = np.array([[2, 0], [0, 1], [10, 5], [2, 1]])
try:
    C = A.dot(B)
    print(f'Матрица AB с размерами {C.shape} из исходных матриц А {A.shape} и В {B.shape}')
    print(C)
    print('---------------')
except:
    print(f'ERROR! Произведение матриц А {A.shape} и В {B.shape} невозможно.')
    print('---------------')

A = np.array([[1, 0, 4 , 2, 1], [2, 1, 0, 4 ,2]])
B = np.array([[2, 0, 4], [0, 1, 2], [10, 5, 12], [2, 1, 9], [0, 1, 2]])
try:
    C = A.dot(B)
    print(f'Матрица AB с размерами {C.shape} из исходных матриц А {A.shape} и В {B.shape}')
    print(C)
    print('---------------')
except:
    print('ERROR!')
    print('---------------')

A = np.array([[2, 0, 4], [0, 1, 2], [10, 5, 12], [2, 1, 9], [0, 1, 2], [2, 0, 4], [0, 1, 2], [10, 5, 12]])
B = np.array([[1, 0, 4 , 2, 1, 0, 4, 9], [2, 1, 0, 4, 2, 0, 4, 9], [1, 0, 4 , 2, 1, 0, 4, 9]])
try:
    C = A.dot(B)
    print(f'Матрица AB с размерами {C.shape} из исходных матриц А {A.shape} и В {B.shape}')
    print(C)
    print('---------------')
except:
    print('ERROR!')
    print('---------------')

A = np.array([[1, 0, 3, 8], [4, 1, 2, 1], [10, 5, 9, 2], [4, 1, 2, 1]])
B = np.array([[4, 1, 2, 1], [10, 5, 9, 2], [6,3,10, 5], [2, 1, 9, 10]])
try:
    C = A.dot(B)
    print(f'Матрица AB с размерами {C.shape} из исходных матриц А {A.shape} и В {B.shape}')
    print(C)
    print('---------------')
except:
    print('ERROR!')
    print('---------------')


ERROR! Произведение матриц А (4, 2) и В (4, 2) невозможно.
---------------
Матрица AB с размерами (2, 3) из исходных матриц А (2, 5) и В (5, 3)
[[46 23 72]
 [12  7 50]]
---------------
Матрица AB с размерами (8, 8) из исходных матриц А (8, 3) и В (3, 8)
[[  6   0  24  12   6   0  24  54]
 [  4   1   8   8   4   0  12  27]
 [ 32   5  88  64  32   0 108 243]
 [ 13   1  44  26  13   0  48 108]
 [  4   1   8   8   4   0  12  27]
 [  6   0  24  12   6   0  24  54]
 [  4   1   8   8   4   0  12  27]
 [ 32   5  88  64  32   0 108 243]]
---------------
Матрица AB с размерами (4, 4) из исходных матриц А (4, 4) и В (4, 4)
[[ 38  18 104  96]
 [ 40  16  46  26]
 [148  64 173  85]
 [ 40  16  46  26]]
---------------


### 1_2

In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A {A.shape}')
print(A)
print(f'Матрица B {B.shape}')
print(B)

print(f'Сумма матриц A и В:')
print(A+B)

print(f'Произведение матриц A и В:')
print(A.dot(B))

Матрица A (2, 2)
[[ 1 -2]
 [ 3  0]]
Матрица B (2, 2)
[[ 4 -1]
 [ 0  5]]
Сумма матриц A и В:
[[ 5 -3]
 [ 3  5]]
Произведение матриц A и В:
[[  4 -11]
 [ 12  -3]]


### 1_3

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Матрица С:')
print(C)
print('Линейная комбинация: 3𝐴−2𝐵+4𝐶')
print('Ответ:')
print((3*A)-(2*B)+(4*C))

Матрица А:
[[ 1  7]
 [ 3 -6]]
Матрица В:
[[ 0  5]
 [ 2 -1]]
Матрица С:
[[ 2 -4]
 [ 1  1]]
Линейная комбинация: 3𝐴−2𝐵+4𝐶
Ответ:
[[ 11  -5]
 [  9 -12]]


### 1_4

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print('Исходная матрица А:')
print(A)
aT = A.T
print('Транспонированная матрица А:')
print(aT)

AaT = A.dot(aT)
print('Произведение исходной матрицы на транспонированную:')
print(AaT)

aTA = aT.dot(A)
print('Произведение транспонированной матрицы на исходную:')
print(aTA)

Исходная матрица А:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица А:
[[ 4  5  2]
 [ 1 -2  3]]
Произведение исходной матрицы на транспонированную:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение транспонированной матрицы на исходную:
[[45  0]
 [ 0 14]]


### 2_1

In [6]:
x = 0
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print('Исходная матрица А:')
print(A)
opr = int(np.linalg.det(A))
print(f'Определитель матрицы: {opr}')
if opr == 0: print(f'Определитель = {opr}, следовательно матрица вырожденная.')

Исходная матрица А:
[[ 0. -1.]
 [ 1.  0.]]
Определитель матрицы: 1


In [7]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print('Исходная матрица А:')
print(A)
opr = int(np.linalg.det(A))
print(f'Определитель матрицы: {opr}')
if opr == 0: print(f'Определитель = {opr}, следовательно матрица вырожденная.')

Исходная матрица А:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель матрицы: 180


In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Исходная матрица А:')
print(A)
opr = int(np.linalg.det(A))
print(f'Определитель матрицы: {opr}')
if opr == 0: print(f'Определитель = {opr}, следовательно матрица вырожденная.')

Исходная матрица А:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель матрицы: 0
Определитель = 0, следовательно матрица вырожденная.


### 2_2

In [9]:
A = np.array([[1, 1], [1, 5]])
print('Исходная матрица А:')
print(A)
opr = int(np.linalg.det(A))
print(f'Определитель матрицы: {opr}')

Aa = int(np.linalg.det(A*A))
AT = int(np.linalg.det(A.T))
AA = int(np.linalg.det(A*2))

print(f'𝑑𝑒𝑡(𝐴^2): {Aa}')
print(f'𝑑𝑒𝑡(𝐴𝑇): {AT}')
print(f'𝑑𝑒𝑡(2𝐴): {AA}')

Исходная матрица А:
[[1 1]
 [1 5]]
Определитель матрицы: 4
𝑑𝑒𝑡(𝐴^2): 24
𝑑𝑒𝑡(𝐴𝑇): 4
𝑑𝑒𝑡(2𝐴): 15


### 2_3

In [10]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
opr = int(np.linalg.det(A))
if opr == 0: print(f'Определитель = {opr}, следовательно матрица вырожденная.')

Определитель = 0, следовательно матрица вырожденная.


### 2_4

In [11]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print('Исходная матрица А:')
print(A)
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Исходная матрица А:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [12]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print('Исходная матрица А:')
print(A)
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Исходная матрица А:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
